### ISSUE TITLE
请根据cc BY-NC-SA协议，修改说辞，不要让人误以为是自创的

### ISSUE THREAD

**Issue by MakerM0** [ChancenJ/TripleKey#1]
首先，非常感谢你对[3plus](https://oshwhub.com/kakaka/Multi-function-macro-keyboard-3Plus20-version)项目的喜爱，

但是，还请遵守原项目开源协议，[署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0)](https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode.zh-Hans)
请给出具体源地址和作者署名，以及修改之处；[https://github.com/MakerM0/3Plus_v2](https://github.com/MakerM0/3Plus_v2)
对于衍生的项目，功能方面的请不要写成重构，毕竟里面的基础框架还是用的我的，请尊重我的劳动成功（毕竟花了大量时间写的）
硬件部分，也是如此，旋钮和按键模型也是用的本人的，或者衍生出来的，主板pcb，框架也无大的改变，除了更改了部分元件和位置

共同维护开源环境，期待你的回复

**Comment by ChancenJ** [comment]
已更新项目文档

**Comment by MakerM0** [comment]
感谢修正，欢迎一同学习进步交流
